### PR TITLE
HBASE-24724: Parallelize make with Yetus

### PR DESCRIPTION
**Pull request by bharathv**
Passes -j$(nproc) args to make compilation.

### CODE REVIEW

**Comment by bharathv** [comment]
@phrocker FYI

**Comment by Apache-HBase** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/hbase-native-client-github-precommit/job/PR-11/1/console in case of problems.

**Comment by bharathv** [comment]
Compilation in pre-commit is currently broken because docker's apt install pulls in an old version of libboost-dev. I'll put up a follow up patch that fixes it. We can atleast verify that -j$(nproc) is being passed along based on jenkins log.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 688 | Docker mode activated. |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +1 | CMakeLists.txt | 1132 | master passed |
||| _ Patch Compile Tests _ |
| +1 | CMakeLists.txt | 314 | the patch passed |
||| _ Other Tests _ |
| | | 2146 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/hbase-native-client-github-precommit/job/PR-11/1/artifact/hbase-native-client-precommit/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-native-client/pull/11 |
| JIRA Issue | HBASE-24724 |
| Optional Tests |  |
| uname | Linux securecluster 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | cmake |
| Personality | bin/hbase-native-client-personality.sh |
| git revision | master / 931ecad |
| Max. process+thread count | 63 (vs. ulimit of 1000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/hbase-native-client-github-precommit/job/PR-11/1/console |
| versions | git=2.7.4 cmake=cmake version 3.5.1 make=GNU Make 4.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by joshelser — APPROVED** [review]
Looks great!

**Comment by phrocker** [comment]
@bharathv LGTM too. Once this is merged and the other PR gets a +1 it should be good. I'll wait for that process to finish. Thanks!

**Comment by bharathv** [comment]
@phrocker Is your other patch ready for review? It seemed like you were adding more changes to it.

**Pull request merged**
